update
upgrade

tap homebrew/versions
tap phinze/homebrew-cask
tap homebrew/binary

install brew-cask
install mysql
install mongodb
install couchdb
install zsh
install git
install tmux
install curl
install vim
install openssl
install wget
install bash-completion
install rbenv
install ruby-build
install rbenv-gemset
install rbenv-gem-rehash
install readline
install apple-gcc42
install pyenv
install pyenv-virtualenv
install gcc47
install ghc --cc=gcc-4.8
install haskell-platform --cc=gcc-4.8

cask install alfred
cask install google-chrome
cask install firefox
cask install virtualbox
cask install vagrant
cask install kobito
cask install bettertouchtool
cask install coteditor
cask install skype

cask alfred link # for Alfred