update
upgrade

tap homebrew/versions
tap homebrew/binary
tap sanemat/font

install mysql
install mongodb
install couchdb
install zsh
install git
install tmux
install curl
install vim
install openssl
install wget
install bash-completion
install mercurial
install rbenv
install ruby-build
install rbenv-gemset
install rbenv-gem-rehash
install readline
install pyenv
install pyenv-virtualenv
install heroku
install redis